### ISSUE TITLE
AttributeError: 'GmailSlurper' object has no attribute 'imap'

### ISSUE THREAD

**Issue by macsilber** [rjurney/Agile_Data_Code#2]
I get the following error 

(venv)vagrant@agiledata:~/agiledata/book-code/ch03/gmail$ ./gmail.py -m automatic -u xxxxxxx@gmail.com -p xxxxxxx -s ./email.avro.schema -f '[Gmail]/All Mail' -o /tmp/test_mbox2
Timeout exception occurred!
Traceback (most recent call last):
  File "./gmail.py", line 104, in <module>
    main()
  File "./gmail.py", line 85, in main
    status, count = slurper.init_folder(imap_folder)
  File "/home/vagrant/agiledata/book-code/ch03/gmail/gmail_slurper.py", line 58, in init_folder
    status, count = self.imap.select(folder)
AttributeError: 'GmailSlurper' object has no attribute 'imap'

**Comment by macsilber** [comment]
Actually this is really an error is pinging out to gmail. Fix that and all works. Error is a little hard to track down in Python, but it basically means domain imap.gmail.com not available. Fix networking and it will be fine.
