### ISSUE TITLE
File "./gmail.py", line 7, in <module>     from lepl.apps.rfc3696 import EmailUtils ImportError: No module named lepl.apps.rfc3696

### ISSUE THREAD

**Issue by saisaigraph** [rjurney/Agile_Data_Code#26]
when i try to run this:

./gmail.py -m automatic -u myemail@gmail.com -p 'pwd' -s ./email.avro.schema -f '[Gmail]/All Mail' -o /tmp/test_mbox 2>&1 &

i get this error:

---

 Traceback (most recent call last):
  File "./gmail.py", line 7, in <module>
    from lepl.apps.rfc3696 import EmailUtils
ImportError: No module named lepl.apps.rfc3696

---

Please let me know if you have any suggestions.
Thanks
Sai

**Comment by rjurney** [comment]
pip install lepl

On Sat, Mar 1, 2014 at 11:52 PM, saisaigraph notifications@github.comwrote:

> when i try to run this:
> 
> ./gmail.py -m automatic -u myemail@gmail.com -p 'pwd' -s
> ./email.avro.schema -f '[Gmail]/All Mail' -o /tmp/test_mbox 2>&1 &
> 
> ## i get this error:
> 
> Traceback (most recent call last):
> File "./gmail.py", line 7, in
> from lepl.apps.rfc3696 import EmailUtils
> 
> ## ImportError: No module named lepl.apps.rfc3696
> 
> Please let me know if you have any suggestions.
> Thanks
> Sai
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/rjurney/Agile_Data_Code/issues/26
> .

## 

Russell Jurney twitter.com/rjurney russell.jurney@gmail.com datasyndrome.com

**Comment by pablomdata** [comment]
Hi, I get timeout exception error immediately after running ./gmail.py... I can connect to imap.gmail.com by telnet.

**Comment by rjurney** [comment]
If you let it keep going, it should work despite the exception. It
reconnects.
ᐧ

On Sat, Mar 7, 2015 at 8:41 AM, pmaldonadolopez notifications@github.com
wrote:

> Hi, I get timeout exception error immediately after running ./gmail.py...
> I can connect to imap.gmail.com by telnet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rjurney/Agile_Data_Code/issues/26#issuecomment-77697172
> .

## 

Russell Jurney twitter.com/rjurney russell.jurney@gmail.com datasyndrome.com

**Comment by pablomdata** [comment]
Hi, thanks for the reply, but it still doesn't work: I get

Folder '[Gmail]/All Mail' SELECT status: NO
Problem initializing imap connection. 

Then it stays there and nothing is copied to the target folder. Any suggestions on how to fix this?

**Comment by austiine04** [comment]
I think you should put you args in quotes eg -u 'username@gmail.com' -p 'password' etc

**Comment by chaowu2009** [comment]
Problem: Warning: /tmp/my_inbox_directory already exists:
Warning: /tmp/my_inbox_directorytmp already exists:
Traceback (most recent call last):
  File "./gmail.py", line 104, in <module>
    main()
  File "./gmail.py", line 85, in main
    status, count = slurper.init_folder(imap_folder)
  File "/home/cwu/Agile_Data_Code/ch03/gmail/gmail_slurper.py", line 68, in init_folder
    status, count = self.imap.select(folder)  
  File "/usr/lib/python2.7/imaplib.py", line 661, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/usr/lib/python2.7/imaplib.py", line 1087, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python2.7/imaplib.py", line 837, in _command
    ', '.join(Commands[name])))
imaplib.error: command SELECT illegal in state NONAUTH, only allowed in states AUTH, SELECTED

**Comment by sprog** [comment]
I am getting the same error as above even after 'sudo pip install lepl':

Traceback (most recent call last):
File "./gmail.py", line 7, in 
from lepl.apps.rfc3696 import EmailUtils
ImportError: No module named lepl.apps.rfc3696

**Comment by sprog** [comment]
I solved the above error:

sudo pip install lepl was pointing to 3.5 instead of 2.7 due to upgrading pip.

sudo python -m pip install lepl

fixed it.
