### ISSUE TITLE
CH03: 'imaplib.error' when getting Gmail Email w/ script:

### ISSUE THREAD

**Issue by quannabe** [rjurney/Agile_Data_Code#33]
The following command (with my username & password):

```
./gmail.py -m automatic -u user@gmail.com -p 'mypassword' -s ./email.avro.schema -f '[Gmail]/All Mail' -o /tmp/test_mbox 2>&1 &
```

And see the following error. Any Ideas?:

```
Traceback (most recent call last):
  File "./gmail.py", line 104, in <module>
    main()
  File "./gmail.py", line 85, in main
    status, count = slurper.init_folder(imap_folder)
  File "/Users/William/github/Agile_Data_Code/ch03/gmail/gmail_slurper.py", line 68, in init_folder
    status, count = self.imap.select(folder)      
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 649, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 1070, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 825, in _command
    ', '.join(Commands[name])))
imaplib.error: command SELECT illegal in state NONAUTH, only allowed in states AUTH, SELECTED
```

**Comment by harishvc** [comment]
I got the same error today morning.

**Comment by quannabe** [comment]
Ok, I believe I know what is going on here.  After trying another Gmail account that does not have 2-Factor Auth enabled, I am not having any issues.

Perhaps it would be helpful to note somewhere that accounts with 2-Factor Auth won't work with this script?

**Comment by harishvc** [comment]
Exactly! Works now.

**Comment by charlielm49** [comment]
Besides 2-Factor Auth disabling, I also had to enable the "less security" option in my gmail account for my script to work

**Comment by apander** [comment]
Charlie is right, you need to "Allow less secure apps: ON" for the connection to gmail

**Comment by ghost** [comment]
"Allow less secure apps: ON" did the trick for me.
