### ISSUE TITLE
Issue getting sent_counts.pig to work

### ISSUE THREAD

**Issue by gammay** [rjurney/Agile_Data_Code#46]
This seems like a trivial enough issue, but stuck for 2 days...

```
~/work/agile_data_science/Agile_Data_Code/ch03/pig$ pig -l /tmp -x local -v -w sent_counts.pig
2015-06-27 12:50:31,890 [main] INFO  org.apache.pig.Main - Apache Pig version 0.11.2-SNAPSHOT (rexported) compiled Jun 27 2015, 12:17:04
2015-06-27 12:50:31,891 [main] INFO  org.apache.pig.Main - Logging error messages to: /tmp/pig_1435389631827.log
2015-06-27 12:50:33,652 [main] INFO  org.apache.pig.impl.util.Utils - Default bootup file /home/cisadmin/.pigbootup not found
2015-06-27 12:50:33,687 [main] INFO  org.apache.pig.tools.parameters.PreprocessorContext - Executing command : echo $HOME/Software/
2015-06-27 12:50:33,928 [main] INFO  org.apache.pig.backend.hadoop.executionengine.HExecutionEngine - Connecting to hadoop file system at: file:///
2015-06-27 12:50:35,252 [main] ERROR org.apache.pig.tools.grunt.Grunt - ERROR 1025:
<file sent_counts.pig, line 18, column 31> Invalid field projection. Projected field [from] does not exist.
2015-06-27 12:50:35,253 [main] ERROR org.apache.pig.tools.grunt.Grunt - org.apache.pig.impl.plan.PlanValidationException: ERROR 1025:
<file sent_counts.pig, line 18, column 31> Invalid field projection. Projected field [from] does not exist.
        at org.apache.pig.newplan.logical.expression.ProjectExpression.findColNum(ProjectExpression.java:183)
        at org.apache.pig.newplan.logical.expression.ProjectExpression.setColumnNumberFromAlias(ProjectExpression.java:166)
...
```

Done till now:
- Followed all steps in ch03
- Tested avro standalone
- Pig is installed (used 0.11.1 itself for simplicity)
- Tested avro is able to read my mail data file correctly:

```
(venv)~/work/agile_data_science$ python test_read_avro.py
{u'bccs': None,
 u'body': u"View this email in your browser\r\n[http://mailer.dzone.com/display.php?M=1636801&C=a8b08717c76733a0b595b9feb67f2798&S=5176&L=3&N=3141]\r\n\r\nDZone [http://mailer.dzone.com/link.php?M=1636801&N=5176&L=80&F=T]\r\n\r\n\r\nFREE RESEARCH GUIDE\r\nDZone Guide to Mobile Development - 2015 EDITION\r\n\r\n\r\nDownload the Guide:\r\n[http://mailer.dzone.com/link.php?M=1636801&N=5176&L=23988&F=T]\r\n\r\n\r\nWHAT'S INSIDE?\r\n\r\n -- Get an expert view of the mobile development landscape: from\r\n     MBaaS to creating the best user experience\r\n\r\n -- Key findings from our survey to over 500 developers that sheds\r\n     light on mobile development trends and patterns\r\n\r\n -- Follow our steps in the Mobile App Testing Checklist for a clear\r\n     process to a successful app\r\n\r\n -- Review our list of the best MADPs and mobile web frameworks\r\n\r\n\r\nREAD YOUR FREE GUIDE\r\n[http://mailer.dzone.com/link.php?M=1636801&N=5176&L=23989&F=T]\r\n\r\n\r\n\r\n\r\nThis email is was sent to: gammay@gmail.com.\r\nUnsubscribe:\r\nhttp://mailer.dzone.com/unsubscribe.php?M=1636801&C=a8b08717c76733a0b595b9feb67f2798&L=3&N=5176\r\n\r\nDZone 150 Preston Executive Dr, Cary, NC 27513\r\n\xa92015 DZone, Inc.\r\n",
 u'ccs': None,
 u'date': u'2015-06-24T10:15:31',
 u'from': {u'address': u'mailer@dzone.com', u'real_name': u'DZone'},
 u'in_reply_to': u'None',
 u'message_id': u'0000014e2510bddf-c8ec36c7-6b97-4d96-b9cb-263917629524-000000@email.amazonses.com',
 u'reply_tos': [{u'address': u'mailer@dzone.com', u'real_name': None}],
 u'subject': u'Gir, how are you overcoming mobile development pain points?',
 u'thread_id': u'1504854338257655678',
 u'tos': [{u'address': u'gammay@gmail.com', u'real_name': u'Gir Man'}]}
....
```

test_read_avro.py:

```
from avro import schema, datafile, io
import pprint

# OUTFILE_NAME = '/tmp/messages.avro'
OUTFILE_NAME = '/home/cisadmin/work/agile_data_science/mails/part-1.avro'

# Test reading avros
rec_reader = io.DatumReader()

# Create a 'data file' (avro file) reader
df_reader = datafile.DataFileReader(
  open(OUTFILE_NAME),
    rec_reader
    )

# Read all records stored inside
pp = pprint.PrettyPrinter()
for record in df_reader:
      pp.pprint(record)
```

sent_counts.pig:

```
/* Set Home Directory - where we install software */
%default HOME `echo \$HOME/Software/`

REGISTER $HOME/pig/build/ivy/lib/Pig/avro-1.5.3.jar
REGISTER $HOME/pig/build/ivy/lib/Pig/json-simple-1.1.jar
REGISTER $HOME/pig/contrib/piggybank/java/piggybank.jar

DEFINE AvroStorage org.apache.pig.piggybank.storage.avro.AvroStorage();

rmf /tmp/sent_counts.txt

/* Load the emails in avro format (edit the path to match where you saved them) using the AvroStorage UDF from Piggybank */
messages = LOAD '$HOME/work/agile_data_science/mails/part-1.avro' USING AvroStorage();
...
```

What could I be missing?

**Comment by gammay** [comment]
As expected, it was a trivial error - the avro file path was not set correctly (The pig script redefines $HOME which added to the confusion)
